=== spiewaj/songbook/_site/song.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://21wdh.staszic.waw.pl" xmlns:xs="http://www.w3.org/2001/XMLSchema"  xmlns:song="http://21wdh.staszic.waw.pl">
    <xs:element name="song" type="song:songType"/>
    <xs:complexType name="creatorType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="solo" />
                            <xs:enumeration value="band" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="chType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="a" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="rowType" mixed="true">
        <xs:sequence>
            <xs:element type="song:chType" name="ch" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="important_over" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"/> <!--Chords should be showed above the lyric-->
                    <xs:enumeration value="false"/><!--Chords may be showed above the lyric (but it's usually not needed)-->
                    <xs:enumeration value="never"/><!--Chords are only shown on the left side-->
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="sidechords" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>
                    Explicit side-margin chords override. Controls the exact text rendered in the side margin
                    (e.g., in LaTeX and HTML margin chords). Allows preferred formatting such as glued chords
                    (e.g., 'DG', 'CC7+') indicating rapid chord changes within a measure, parentheses
                    (e.g., '(D)', '(H7)') for passing or optional chords, and bar dividers ('|').
                    Co-exists with inline &lt;ch&gt; tags (which control placement above lyrics words).
                    Do not remove when adding or refining inline chords.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="style" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="instr" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="blockType" mixed="true">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element type="song:rowType" name="row" maxOccurs="unbounded" minOccurs="0" />
            <xs:element type="song:bisType" name="bis" maxOccurs="unbounded" minOccurs="0" />
        </xs:choice>
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string" >
                    <xs:enumeration value="verse" />
                    <xs:enumeration value="chorus" />
                    <xs:enumeration value="other" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>


    <xs:complexType name="bisType">
        <xs:sequence>
            <xs:element type="song:rowType" name="row" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
        <xs:attribute type="xs:integer" name="times" use="optional"/>
    </xs:complexType>

    <xs:complexType name="blocklinkType">
        <xs:attribute type="xs:integer" name="blocknb" use="required"/>
    </xs:complexType>

    <xs:complexType name="lyricType">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element type="song:blockType" name="block" maxOccurs="unbounded" minOccurs="0" />
            <xs:element type="song:blocklinkType" name="blocklink" maxOccurs="unbounded" minOccurs="0"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="guitarType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:byte" name="barre"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="musicType">
        <xs:all>
            <xs:element type="song:guitarType" name="guitar" minOccurs="0" maxOccurs="1"/>
        </xs:all>
        <xs:attribute type="xs:string" name="metre" use="optional"/>
    </xs:complexType>
    <xs:complexType name="keywordsType">
        <xs:sequence>
            <xs:element type="xs:string" name="keyword" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="doneType">
        <xs:all>
            <xs:element type="xs:string" name="text" maxOccurs="1" minOccurs="0"/>
            <xs:element type="xs:string" name="chords" maxOccurs="1" minOccurs="0"/>
            <xs:element type="xs:string" name="authors" maxOccurs="1" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="verificatorsType">
        <xs:annotation>
            <xs:documentation>
                Historical track record of editorial verification and corrections.
                Existing &lt;verificator&gt; entries must NOT be deleted. New verification notes
                and source URLs/references should always be appended.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="xs:string" name="verificator" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="statusType">
        <xs:all>
            <xs:element type="song:doneType" name="done" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:verificatorsType" name="verificators"  minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="to_do"  minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="songType">
        <xs:all>
            <xs:element type="xs:string" name="alias" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:creatorType" name="text_author" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="comment" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:creatorType" name="composer" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:creatorType" name="artist" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="translator" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="original_title" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:lyricType" name="lyric" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:musicType" name="music" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:keywordsType" name="keywords" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="album" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="genre" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:statusType" name="status" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="music_source" minOccurs="0" maxOccurs="1"/>
        </xs:all>
        <xs:attribute type="xs:string" name="title" use="required"/>
        <xs:attribute name="lang" type="xs:string" use="optional" default="pl">
            <xs:annotation>
                <xs:documentation>Language code (e.g., 'pl', 'en', 'de', 'fr')</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== spiewaj/songbook/songs/pl/poezja/Dom_wschodzacego_slonca.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Dom wschodzącego słońca">
	<alias/>
	<text_author type="solo">tradycyjny</text_author>
	<comment>Polska wersja ogniskowa amerykańskiej ballady „The House of the Rising Sun”.</comment>
	<composer type="solo">tradycyjna</composer>
	<artist type="band">The Animals</artist>
	<translator>autor nieznany</translator>
	<original_title>The House of the Rising Sun</original_title>
	<lyric>
		<block type="verse">
			<row important_over="true">Przez ci<ch a="a"/>emne szyby zagl<ch a="C"/>ąda już mr<ch a="D"/>ok, <ch a="F"/></row>
			<row important_over="true">w łóż<ch a="a"/>eczku mały chł<ch a="C"/>opiec śp<ch a="E"/>i. <ch a="E7"/></row>
			<row important_over="true">S<ch a="a"/>en jakiś dziwny wykrzk<ch a="C"/>ywił mu tw<ch a="D"/>arz, <ch a="F"/></row>
			<row important_over="true">p<ch a="a"/>od powiek<ch a="E"/>ami lśnią łz<ch a="a"/>y. <ch a="E"/></row>
		</block>
		<block type="verse">
			<row>Wcz<ch a="a"/>oraj wieczorem dow<ch a="C"/>iedział się, ż<ch a="D"/>e <ch a="F"/></row>
			<row>j<ch a="a"/>est w Orleanie t<ch a="C"/>aki d<ch a="E"/>om, <ch a="E7"/></row>
			<row>Wsch<ch a="a"/>odzącym Słońcem naz<ch a="C"/>ywa się g<ch a="D"/>o, <ch a="F"/></row>
			<row>mi<ch a="a"/>eszkają w n<ch a="E"/>im chłopcy jak <ch a="a"/>on. <ch a="E"/></row>
		</block>
		<block type="verse">
			<row>W <ch a="a"/>oknach ma kraty, przy drzwi<ch a="C"/>ach stoi str<ch a="D"/>óż <ch a="F"/></row>
			<row>i p<ch a="a"/>atrzy wzrokiem pon<ch a="C"/>ur<ch a="E"/>ym <ch a="E7"/></row>
			<row>n<ch a="a"/>a małych chłopców, więzi<ch a="C"/>enny ich str<ch a="D"/>ój, <ch a="F"/></row>
			<row>n<ch a="a"/>a ogol<ch a="E"/>one gł<ch a="a"/>owy. <ch a="E"/></row>
		</block>
		<block type="verse">
			<row>A<ch a="a"/>le nadzieja nie zg<ch a="C"/>aśnie w n<ch a="D"/>ich <ch a="F"/></row>
			<row>pom<ch a="a"/>imo więziennych m<ch a="C"/>urów c<ch a="E"/>el, <ch a="E7"/></row>
			<row>wsch<ch a="a"/>odzące słońce zabł<ch a="C"/>yśnie zn<ch a="D"/>ów <ch a="F"/></row>
			<row>n<ch a="a"/>ad małym d<ch a="E"/>omem w kraju t<ch a="a"/>ym. <ch a="E"/></row>
		</block>
	</lyric>
	<music metre="6/8">
		<guitar barre="0"/>
	</music>
	<keywords/>
	<album/>
	<genre>Folk</genre>
	<status>
		<done>
			<text/>
			<authors/>
			<chords>chord positioning</chords>
		</done>
		<verificators>
			<verificator>Amerykańska ballada tradycyjna „The House of the Rising Sun”</verificator>
			<verificator>Polska wersja ogniskowa (autor przekładu nieznany)</verificator>
			<verificator>https://spiewnik.wywrota.pl/piosenki-harcerskie/dom-wschodzacego-slonca</verificator>
		</verificators>
	</status>
	<music_source/>
</song>

=== spiewaj/songbook/songs/pl/poezja/Madonna.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Madonna">
	<alias>Polsko-ruska madonna</alias>
	<text_author type="solo">Tadeusz Kubiak</text_author>
	<comment></comment>
	<composer type="solo">Józef Kołodziejczyk</composer>
	<artist type="band">Bez Jacka</artist>
	<translator/>
	<original_title/>
	<lyric>
		<block type="chorus">
			<row important_over="true">P<ch a="F"/>olsko-r<ch a="G"/>uska mad<ch a="a"/>onna,</row>
			<row important_over="true">P<ch a="F"/>olsko-st<ch a="G"/>arocerki<ch a="a"/>ewna,</row>
			<row important_over="true"><ch a="F"/> Z gorejąc<ch a="G"/>ego zł<ch a="a"/>ota,</row>
			<row important_over="true">Z ż<ch a="F"/>ywego dr<ch a="G"/>ewna, sr<ch a="a"/>ebra.</row>
		</block>
		<block type="verse">
			<row important_over="true"><ch a="F"/> Bizant<ch a="G"/>yjsko-słowi<ch a="d"/>ańska,</row>
			<row important_over="false"><ch a="F"/> W śnieżnobi<ch a="G"/>ałych suki<ch a="d"/>enkach,</row>
			<row important_over="false"><ch a="F"/> Nie na biel<ch a="G"/>onych pł<ch a="d"/>ótnach,</row>
			<row important_over="true"><ch a="C"/> Na trumiennych d<ch a="G"/>eskach.</row>
		</block>
		<blocklink blocknb="1"/>
		<block type="verse">
			<row important_over="false"><ch a="F"/> Nie boj<ch a="G"/>arska, nie c<ch a="d"/>arska,</row>
			<row important_over="false"><ch a="F"/> Zasmuc<ch a="G"/>ona, kami<ch a="d"/>enna twarz,</row>
			<row important_over="false"><ch a="F"/> Nie boj<ch a="G"/>arska, nie c<ch a="d"/>arska,</row>
			<row important_over="false">Zasmuc<ch a="C"/>ona, chłopska ik<ch a="G"/>ona.</row>
		</block>
		<blocklink blocknb="1"/>
	</lyric>
	<music metre="4/4">
		<guitar barre="0"/>
	</music>
	<keywords/>
	<album>Zatańcz ze mną na polanie</album>
	<genre>Poezja śpiewana</genre>
	<status>
		<done>
			<text/>
			<authors/>
			<chords>chord positioning</chords>
		</done>
		<verificators>
			<verificator>Alek</verificator>
			<verificator>Paweł Budzyński</verificator>
		</verificators>
		<to_do/>
	</status>
	<music_source/>
</song>

=== spiewaj/songbook/songs/pl/poezja/Piosenka_o_papierowym_zolnierzyku.xml
<?xml version="1.0" encoding="UTF-8"?>
<song title="Piosenka o papierowym żołnierzyku" xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd">
	<alias>Raz pewien żołnierz sobie żył</alias>
	<text_author type="solo">Bułat Okudżawa</text_author>
	<comment></comment>
	<composer type="solo">Bułat Okudżawa</composer>
	<artist type="solo">Bułat Okudżawa</artist>
	<translator>Witold Dąbrowski</translator>
	<original_title>Piesienka o bumażnam sałdatie</original_title>
	<lyric xmlns="http://21wdh.staszic.waw.pl">
		<block type="verse">
			<row important_over="true">Raz p<ch a="a"/>ewien żołnierz sobie żył,</row>
			<row important_over="true">odw<ch a="a"/>ażny i zawzi<ch a="E"/>ęty,</row>
			<row important_over="true">lecz c<ch a="E"/>óż?… zabawką tylko był,</row>
			<row important_over="true">z kart<ch a="E"/>onu był wyci<ch a="a"/>ęty.</row>
		</block>
		<block type="verse">
			<row important_over="false">Choć zmi<ch a="a"/>eniać świat i zwalczać zło</row>
			<row important_over="false">niezmi<ch a="a"/>ennie był got<ch a="E"/>owy,</row>
			<row important_over="false">stał ci<ch a="E"/>ągle wśród zabawek, bo</row>
			<row important_over="false">był t<ch a="E"/>ylko papier<ch a="a"/>owy.</row>
		</block>
		<block type="verse">
			<row important_over="false">I w <ch a="a"/>ogień gotów był, jak w dym,</row>
			<row important_over="false">pójść z<ch a="a"/>a Was bez nam<ch a="E"/>owy,</row>
			<row important_over="false">i mi<ch a="E"/>eliście sto pociech z nim —</row>
			<row important_over="false">bo b<ch a="E"/>ył on papier<ch a="a"/>owy.</row>
		</block>
		<block type="verse">
			<row important_over="false">I ni<ch a="a"/>e ujawniał przed nim sztab</row>
			<row important_over="false">taj<ch a="a"/>emnic swych wojsk<ch a="E"/>owych.</row>
			<row important_over="false">A cz<ch a="E"/>emu tak? A temu tak,</row>
			<row important_over="false">że b<ch a="E"/>ył on papier<ch a="a"/>owy.</row>
		</block>
		<block type="verse">
			<row important_over="false">Wyz<ch a="a"/>ywał los, w pogardzie miał</row>
			<row important_over="false">tchórzl<ch a="a"/>iwych marud<ch a="E"/>erów,</row>
			<row important_over="false">i „<ch a="E"/>Ognia! Ognia!” ciągle łkał,</row>
			<row important_over="false">choć prz<ch a="E"/>ecież był z papi<ch a="a"/>eru.</row>
		</block>
		<block type="verse">
			<row important_over="false">Niej<ch a="a"/>eden wódz już w ogniu znikł,</row>
			<row important_over="false">niej<ch a="a"/>eden szereg<ch a="E"/>owy…</row>
			<row important_over="false">i p<ch a="E"/>oszedł w ogień… Zginął w mig</row>
			<row important_over="false">żołni<ch a="E"/>erzyk papier<ch a="a"/>owy.</row>
		</block>
	</lyric>
	<music metre="4/4">
		<guitar barre="0"/>
	</music>
	<keywords></keywords>
	<album>Do widzenia, chłopcy (Do swidanija, malczyki)</album>
	<genre>poezja śpiewana</genre>
	<status>
		<done>
			<text/>
			<authors/>
			<chords>chord positioning</chords>
		</done>
		<verificators>
			<verificator>Michał Korch</verificator>
			<verificator>Krzysiek Cz.</verificator>
			<verificator>Piotr Tabernacki</verificator>
		</verificators>
		<to_do></to_do>
	</status>
	<music_source></music_source>
</song>

=== spiewaj/songbook/songs/pl/poezja/Piosenka_bez_tytulu.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Piosenka bez tytułu">
  <alias>Jeszcze się tyle stanie</alias>
  <text_author type="solo">Waldemar Chyliński</text_author>
  <comment>Oryginalna tonacja utworu (Adam Drąg) to e-moll [e G / a H7 / C G H7; refren: H7 e / H7 e / C G H7].</comment>
  <composer type="solo">Adam Drąg</composer>
  <artist type="solo">Adam Drąg</artist>
  <translator></translator>
  <original_title></original_title>
  <lyric>
    <block type="verse">
      <row important_over="true"><ch a="a"/>Popatrz, niebo się kłania, <ch a="C"/></row>
      <row important_over="true">n<ch a="d"/>iebo róż<ch a="E7"/>owe,</row>
      <row important_over="true"><ch a="F"/>wiatrem sypane w ko<ch a="C"/>lorze...<ch a="E"/></row>
      <row important_over="false"><ch a="a"/>Słońce przy<ch a="C"/>chodzi</row>
      <row important_over="false">j<ch a="d"/>ak gość naj<ch a="E7"/>lepszy,</row>
      <row important_over="false"><ch a="F"/>wiatr się umila na <ch a="C"/>wietrzyk...<ch a="E"/></row>
    </block>
    <block type="chorus">
      <bis times="2">
        <row important_over="true"><ch a="E7"/>Jeszcze się tyle <ch a="a"/>stanie,</row>
        <row important_over="false"><ch a="E7"/>jeszcze się tyle <ch a="a"/>zmieni,</row>
        <row important_over="true"><ch a="F"/>rosną nam nowe <ch a="C"/>twarze</row>
        <row important_over="true">do <ch a="E7"/>słońca.</row>
      </bis>
    </block>
    <block type="verse">
      <row important_over="false"><ch a="a"/>Popatrz, drzewo się czesze, <ch a="C"/></row>
      <row important_over="false">d<ch a="d"/>rzewo olbrz<ch a="E7"/>ymie,</row>
      <row important_over="false">po <ch a="F"/>niebie gałęźmi wiatr <ch a="C"/>pisze...<ch a="E"/></row>
      <row important_over="false"><ch a="a"/>Rzeka się <ch a="C"/>śmieje</row>
      <row important_over="false">d<ch a="d"/>obrą now<ch a="E7"/>iną,</row>
      <row important_over="false">i <ch a="F"/>wszystkie żale od<ch a="C"/>płyną...<ch a="E"/></row>
    </block>
    <blocklink blocknb="2"/>
  </lyric>
  <music metre="4/4">
    <guitar barre="0"/>
  </music>
  <keywords></keywords>
  <album></album>
  <genre>poezja śpiewana</genre>
  <status>
    <done>
      <text/>
      <authors/>
      <chords>chord positioning</chords>
    </done>
    <verificators/>
    <to_do></to_do>
  </status>
  <music_source>Śpiewnik Wywroty (sł. Waldemar Chyliński, muz. Adam Drąg)</music_source>
</song>

=== spiewaj/songbook/songs/en/A_Wee_drap_O_Whisky.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="A  Wee drap O&#039; Whisky" lang="en">
	<lyric>
		<block type="verse">
			<row important_over="true">A <ch a="fis"/>wee drappie whisky, oh w<ch a="D"/>hen I am w<ch a="fis"/>earied</row>
			<row important_over="true"><ch a="A"/>Ma blood it w<ch a="fis"/>ill warm, my sp<ch a="A"/>irits will ch<ch a="E7"/>eer</row>
			<row important_over="true">For w<ch a="fis"/>hen I sit doon, I intend to be m<ch a="E7"/>erry</row>
			<row important_over="true">Come f<ch a="A"/>ill up a bumper and h<ch a="D"/>and it round <ch a="fis"/>here.</row>
		</block>
		<block type="verse">
			<row important_over="false">I can scarce get a hauf oor, oh when I am wearied<ch a="fis"/><ch a="D"/><ch a="fis"/></row>
			<row important_over="false">To tell you the truth that I&#039;m vrocht (wrought) very sore<ch a="A"/><ch a="fis"/><ch a="A"/><ch a="E7"/></row>
			<row important_over="false">My ploo and my lassie is a&#039; my whole pleasure<ch a="fis"/><ch a="E7"/></row>
			<row important_over="false">We&#039;ll both tak&#039; a kiss an&#039; hae a drap more.<ch a="A"/><ch a="D"/><ch a="fis"/></row>
		</block>
		<block type="verse">
			<row important_over="false">Contented I sit and contented I labour<ch a="fis"/><ch a="D"/><ch a="fis"/></row>
			<row important_over="false">Contented I drink and contented I sing<ch a="A"/><ch a="fis"/><ch a="A"/><ch a="E7"/></row>
			<row important_over="false">I never dispute nor fall oot wi&#039; my neebors<ch a="fis"/><ch a="E7"/></row>
			<row important_over="false">For that is a mean and a contentious thing.<ch a="A"/><ch a="D"/><ch a="fis"/></row>
		</block>
		<block type="verse">
			<row important_over="false">Oh few, very few ever hear me compleenin<ch a="fis"/><ch a="D"/><ch a="fis"/></row>
			<row important_over="false">Though ofttimes the load of oppression I bear<ch a="A"/><ch a="fis"/><ch a="A"/><ch a="E7"/></row>
			<row important_over="false">Oh fat is the use o a man aye compleenin&#039;<ch a="fis"/><ch a="E7"/></row>
			<row important_over="false">For aye fan he tastes, he maun hae a drap mair.<ch a="A"/><ch a="D"/><ch a="fis"/></row>
		</block>
		<block type="verse">
			<row important_over="false">Come noble waiter, bring in a large measure,<ch a="fis"/><ch a="D"/><ch a="fis"/></row>
			<row important_over="false">I mean hauf a mutchkin the best o&#039; the toon<ch a="A"/><ch a="fis"/><ch a="A"/><ch a="E7"/></row>
			<row important_over="false">An&#039; when it is drunken, it&#039;s time to bejoggin<ch a="fis"/><ch a="E7"/></row>
			<row important_over="false">We&#039;ll gang merrily hame wi&#039; the canniest carl.<ch a="A"/><ch a="D"/><ch a="fis"/></row>
		</block>
		<block type="verse">
			<row important_over="false">So good night to you all, I think it&#039;s but reason,<ch a="fis"/><ch a="D"/><ch a="fis"/></row>
			<row important_over="false">Altho&#039; that the whisky speaks lood in my ear<ch a="A"/><ch a="fis"/><ch a="A"/><ch a="E7"/></row>
			<row important_over="false">Good night and safe home, till farther occasion<ch a="fis"/><ch a="E7"/></row>
			<row important_over="false">We&#039;ll a&#039; meet in friends and hae a drap mair.<ch a="A"/><ch a="D"/><ch a="fis"/></row>
		</block>
	</lyric>
	<keywords/>
	<status>
		<done/>
		<verificators>
			<verificator>Krzysiek Cz.</verificator>
		</verificators>
	</status>
	<music_source>piosenka szkocka</music_source>
</song>

=== spiewaj/songbook/songs/pl/pop/dziwna_daria.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Dziwna">
  <artist type="band">Daria Zawiałow</artist>
  <lyric>
    <block type="verse">
      <row important_over="true"><ch a="G"/>Może chciałbym <ch a="d"/>uczyć się</row>
      <row important_over="false"><ch a="G"/>Jesteś taka nie<ch a="d"/>zastąpiona</row>
      <row important_over="false"><ch a="G"/>Może nie pójdę <ch a="d"/>więcej tam</row>
      <row important_over="true"><ch a="F"/>Wiesz, tak długo <ch a="C"/>byłem sam</row>
      <row important_over="false"><ch a="G"/>Chciałbym, żebyś zau<ch a="d"/>fała mi</row>
      <row important_over="false"><ch a="G"/>Wiem, że przeze mnie <ch a="d"/>czasem płaczesz</row>
      <row important_over="false"><ch a="G"/>Jutro chciałbyś <ch a="d"/>mieć na dziś</row>
      <row important_over="false"><ch a="F"/>Może mi bra<ch a="C"/>kuje sił</row>
    </block>
    <block type="chorus">
      <row important_over="false">Ty <ch a="G"/>wiesz, że kocham <ch a="d"/>cię, </row>
      <row important_over="false">lecz sama <ch a="F"/>jestem dziwna<ch a="C"/></row>
      <row important_over="false">Dziś tylko <ch a="G"/>słowa, twoje <ch a="d"/>słowa </row>
      <row important_over="false">będą <ch a="F"/>leczyć mnie<ch a="C"/></row>
      <row important_over="true">Ty <ch a="G"/>wiesz, że chciała<ch a="d"/>bym nie patrzeć <ch a="F"/>wstecz, </row>
      <row important_over="true">nie szukać<ch a="C"/></row>
      <row important_over="false">Lecz tylko <ch a="G"/>słowa, tylko <ch a="d"/>słowa </row>
      <row important_over="false">nie wys<ch a="F"/>tarczą mi<ch a="C"/></row>
    </block>
    <block type="verse">
      <row important_over="false"><ch a="G"/>Jestem z tym po <ch a="d"/>prostu sam</row>
      <row important_over="false"><ch a="G"/>Nigdy nie byłem tak <ch a="d"/>zakochany</row>
      <row important_over="false"><ch a="G"/>Dziewczyno, przecież <ch a="d"/>znam twój plan</row>
      <row important_over="false"><ch a="F"/>Musisz jeszcze <ch a="C"/>dać mi czas</row>
      <row important_over="false"><ch a="G"/>Jakbym miał bez <ch a="d"/>ciebie żyć</row>
      <row important_over="false"><ch a="G"/>Przy tobie mogę spać <ch a="d"/>z jaszczurkami</row>
      <row important_over="false"><ch a="G"/>Śniło mi się, że miel<ch a="d"/>iśmy dom</row>
      <row important_over="false"><ch a="F"/>Może ty zrób <ch a="C"/>pierwszy krok</row>
    </block>
    <blocklink blocknb="2"/>
    <block type="verse">
      <row important_over="true"><ch a="G"/>Wiemy, ze nie ch<ch a="G"/>cemy już bez <ch a="d"/>siebie żyć<ch a="d"/></row>
      <row important_over="false"><ch a="G"/>Znów jesteśmy <ch a="G"/>po tej samej <ch a="d"/>stronie<ch a="d"/></row>
      <row important_over="false"><ch a="G"/>Na tapecie <ch a="G"/>już powoli <ch a="d"/>słychać dzień<ch a="d"/></row>
      <row important_over="false">Kiedy <ch a="G"/>jednym <ch a="G"/>staną się dwa <ch a="d"/>domy<ch a="d"/></row>
    </block>
  </lyric>
  <keywords/>
  <genre>Pop</genre>
  <status>
    <done/>
    <verificators/>
  </status>
</song>

=== spiewaj/songbook/songs/pl/harc/pechowy_dzien.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Pechowy dzień">
  <alias>Wiatr i chmura</alias>
  <text_author type="solo">Waldemar Chyliński</text_author>
  <comment/>
  <composer type="solo">Waldemar Chyliński</composer>
  <artist type="band">Smutne Skutki</artist>
  <lyric>
    <block type="verse">
      <row important_over="true"><ch a="D"/>Wiatr przystojny w garniturze</row>
      <row important_over="true"><ch a="a"/>chce spodobać się złej chmurze,</row>
      <row important_over="true">chm<ch a="G"/>ura w złości deszczem go przep<ch a="D"/>ędza.</row>
      <row important_over="false"><ch a="D"/>Wiatr się schował w jakimś oknie,</row>
      <row important_over="false">j<ch a="a"/>est szczęśliwy, że nie moknie,</row>
      <row important_over="false"><ch a="G"/>a miał wkrótce chmurze być za m<ch a="D"/>ęża.</row>
    </block>
    <block type="chorus">
      <bis times="2">
        <row important_over="true"><ch a="F"/>Lecz nie jest źl<ch a="C"/>e,</row>
        <row important_over="true"><ch a="A7"/>mogło być g<ch a="d"/>orzej,</row>
        <row important_over="true">czasem w ż<ch a="F"/>yciu zdarza si<ch a="C"/>ę</row>
        <row important_over="true">pechowy dzi<ch a="D"/>eń.</row>
      </bis>
      <row important_over="false" style="instr"><ch a="D"/><ch a="a"/><ch a="G"/><ch a="D"/><ch a="D"/><ch a="a"/><ch a="G"/><ch a="D"/></row>
    </block>
    <block type="verse">
      <row important_over="false"><ch a="D"/>Wiatr szczęśliwy w wolnym stanie,</row>
      <row important_over="false"><ch a="a"/>zawsze stać go na zawianie,</row>
      <row important_over="false">z<ch a="G"/>awsze stać go na samotny sp<ch a="D"/>acer.</row>
      <row important_over="false"><ch a="D"/>A niejedna chmura teraz</row>
      <row important_over="false">k<ch a="a"/>ocha, cierpi i umiera,</row>
      <row important_over="false">m<ch a="G"/>ówiąc: „Wietrze, mogło być in<ch a="D"/>aczej”.</row>
    </block>
    <blocklink blocknb="2"/>
  </lyric>
  <music metre="4/4">
    <guitar barre="0"/>
  </music>
  <keywords/>
  <genre>Piosenka turystyczna</genre>
  <status>
    <done>
      <authors/>
      <chords>chord positioning</chords>
      <text/>
    </done>
    <verificators>
      <verificator>https://spiewnik.wywrota.pl/waldemar-chylinski/pechowy-dzien</verificator>
    </verificators>
  </status>
</song>
