=== spiewaj/songbook/_site/song.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://21wdh.staszic.waw.pl" xmlns:xs="http://www.w3.org/2001/XMLSchema"  xmlns:song="http://21wdh.staszic.waw.pl">
    <xs:element name="song" type="song:songType"/>
    <xs:complexType name="creatorType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="solo" />
                            <xs:enumeration value="band" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="chType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="a" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="rowType" mixed="true">
        <xs:sequence>
            <xs:element type="song:chType" name="ch" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="important_over" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"/> <!--Chords should be showed above the lyric-->
                    <xs:enumeration value="false"/><!--Chords may be showed above the lyric (but it's usually not needed)-->
                    <xs:enumeration value="never"/><!--Chords are only shown on the left side-->
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="sidechords" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>
                    Explicit side-margin chords override. Controls the exact text rendered in the side margin
                    (e.g., in LaTeX and HTML margin chords). Allows preferred formatting such as glued chords
                    (e.g., 'DG', 'CC7+') indicating rapid chord changes within a measure, parentheses
                    (e.g., '(D)', '(H7)') for passing or optional chords, and bar dividers ('|').
                    Co-exists with inline &lt;ch&gt; tags (which control placement above lyrics words).
                    Do not remove when adding or refining inline chords.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="style" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="instr" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="blockType" mixed="true">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element type="song:rowType" name="row" maxOccurs="unbounded" minOccurs="0" />
            <xs:element type="song:bisType" name="bis" maxOccurs="unbounded" minOccurs="0" />
        </xs:choice>
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string" >
                    <xs:enumeration value="verse" />
                    <xs:enumeration value="chorus" />
                    <xs:enumeration value="other" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>


    <xs:complexType name="bisType">
        <xs:sequence>
            <xs:element type="song:rowType" name="row" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
        <xs:attribute type="xs:integer" name="times" use="optional"/>
    </xs:complexType>

    <xs:complexType name="blocklinkType">
        <xs:attribute type="xs:integer" name="blocknb" use="required"/>
    </xs:complexType>

    <xs:complexType name="lyricType">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element type="song:blockType" name="block" maxOccurs="unbounded" minOccurs="0" />
            <xs:element type="song:blocklinkType" name="blocklink" maxOccurs="unbounded" minOccurs="0"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="guitarType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:byte" name="barre"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="musicType">
        <xs:all>
            <xs:element type="song:guitarType" name="guitar" minOccurs="0" maxOccurs="1"/>
        </xs:all>
        <xs:attribute type="xs:string" name="metre" use="optional"/>
    </xs:complexType>
    <xs:complexType name="keywordsType">
        <xs:sequence>
            <xs:element type="xs:string" name="keyword" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="doneType">
        <xs:all>
            <xs:element type="xs:string" name="text" maxOccurs="1" minOccurs="0"/>
            <xs:element type="xs:string" name="chords" maxOccurs="1" minOccurs="0"/>
            <xs:element type="xs:string" name="authors" maxOccurs="1" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="verificatorsType">
        <xs:annotation>
            <xs:documentation>
                Historical track record of editorial verification and corrections.
                Existing &lt;verificator&gt; entries must NOT be deleted. New verification notes
                and source URLs/references should always be appended.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="xs:string" name="verificator" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="statusType">
        <xs:all>
            <xs:element type="song:doneType" name="done" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:verificatorsType" name="verificators"  minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="to_do"  minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="songType">
        <xs:all>
            <xs:element type="xs:string" name="alias" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:creatorType" name="text_author" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="comment" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:creatorType" name="composer" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:creatorType" name="artist" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="translator" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="original_title" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:lyricType" name="lyric" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:musicType" name="music" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:keywordsType" name="keywords" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="album" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="genre" minOccurs="0" maxOccurs="1"/>
            <xs:element type="song:statusType" name="status" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="music_source" minOccurs="0" maxOccurs="1"/>
        </xs:all>
        <xs:attribute type="xs:string" name="title" use="required"/>
        <xs:attribute name="lang" type="xs:string" use="optional" default="pl">
            <xs:annotation>
                <xs:documentation>Language code (e.g., 'pl', 'en', 'de', 'fr')</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== spiewaj/songbook/songs/pl/pop/warszawa_tlove.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Warszawa">
  <comment/>
  <artist type="band">T.Love</artist>
  <lyric>
    <block type="verse">
      <row important_over="true">Za <ch a="G"/>oknem zimowo zaczyna się dzień</row>
      <row important_over="true">Za<ch a="a"/>czynam kolejny dzień ży<ch a="F"/>cia</row>
      <row important_over="true">Wy<ch a="G"/>glądam przez okno, na oczach mam sen</row>
      <row important_over="true">A <ch a="a"/>Grochów się budzi z przepi<ch a="F"/>cia</row>
      <row important_over="true">Wy<ch a="G"/>pity alkohol uderza w tętnice</row>
      <row important_over="true">Au<ch a="a"/>tobus tapla się w śnie<ch a="F"/>gu</row>
      <row important_over="true">Z<ch a="G"/>za szyby oglądam betonu stolicę</row>
      <row important_over="true">Już<ch a="a"/> jestem na drugim jej brze<ch a="F"/>gu</row>
    </block>
    <block type="chorus">
      <row important_over="true">Gdy <ch a="C"/>patrzę w twe <ch a="G"/>oczy, zmę<ch a="a"/>czone jak <ch a="F"/>moje</row>
      <row important_over="true">To <ch a="C"/>kocham to<ch a="G"/> miasto, zmę<ch a="a"/>czone jak <ch a="F"/> ja</row>
      <row important_over="true">Gdzie <ch a="C"/> Hitler i <ch a="G"/> Stalin zro<ch a="a"/>bili, co <ch a="F"/>swoje</row>
      <row important_over="true">Gdzie <ch a="C"/>wiosna <ch a="G"/>spaliną <ch a="F"/>oddycha</row>
    </block>
    <block type="verse">
      <row important_over="false">Kra<ch a="G"/>kowskie Przedmieście zalane jest słońcem</row>
      <row important_over="false">Wi<ch a="a"/>rujesz jak obłok, wy<ch a="F"/>nurzasz się z bramy</row>
      <row important_over="false">A<ch a="G"/> ja jestem głodny, tak bardzo głodny</row>
      <row important_over="false">Ko<ch a="a"/>chanie, nakarmisz mnie <ch a="F"/>snami</row>
      <row important_over="false">Zi<ch a="G"/>elony Żoliborz, pieprzony Żoliborz</row>
      <row important_over="false">Roz<ch a="a"/>kwita na drzewach, na krze<ch a="F"/>wach</row>
      <row important_over="false">Ście<ch a="G"/>kami z rzeki kompletnie pijany</row>
      <row important_over="false">Chcę <ch a="a"/>krzyczeć, chcę ryczeć, chcę ś<ch a="F"/>piewać</row>
    </block>
    <blocklink blocknb="2"/>
    <block type="other">
      <row important_over="never"/>
      <bis times="4">
        <row important_over="false" style="instr"> <ch a="G"/><ch a="a"/><ch a="F"/></row>
      </bis>
      <row important_over="false" style="instr"> <ch a="C"/><ch a="G"/><ch a="C"/><ch a="G"/><ch a="C"/><ch a="G"/><ch a="C"/><ch a="G"/><ch a="C"/><ch a="G"/><ch a="C"/></row>
      <row important_over="false" style="instr"> <ch a="C"/><ch a="G"/><ch a="C"/><ch a="G"/><ch a="C"/><ch a="G"/><ch a="C"/><ch a="G"/><ch a="F"/><ch a="F"/></row>
    </block>
    <block type="verse">
      <row important_over="false">Je<ch a="G"/>sienią zawsze zaczyna się szkoła</row>
      <row important_over="false">A w k<ch a="a"/>najpach zaczyna się <ch a="F"/>picie</row>
      <row important_over="false">Jest <ch a="G"/>tłoczno i duszno, olewa nas kelner</row>
      <row important_over="false">I <ch a="a"/>tak skończymy o ś<ch a="F"/>wicie</row>
      <row important_over="false">Je<ch a="G"/>sienią zawsze myślę o latach</row>
      <row important_over="false">Tak <ch a="a"/>starych, jak te kamie<ch a="F"/>nice</row>
      <row important_over="false">Je<ch a="G"/>sienią o zmroku przechodzę z tobą</row>
      <row important_over="false">Przez <ch a="a"/>pełne kasztanów ul<ch a="F"/>ice</row>
    </block>
    <blocklink blocknb="2"/>
  </lyric>
  <keywords/>
  <genre>Rock</genre>
  <status>
    <done/>
    <verificators/>
  </status>
</song>

=== spiewaj/songbook/songs/pl/pop/Winda_do_nieba.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Windą do nieba">
  <alias>Mój piękny panie</alias>
  <text_author>Marek Dutkiewicz</text_author>
  <comment>Piosenka z albumu „Teatr na drodze” (1978), jeden z największych przebojów zespołu 2 plus 1.</comment>
  <composer>Janusz Kruk</composer>
  <artist type="band">2 plus 1</artist>
  <lyric>
    <block type="verse">
      <row important_over="true">Mój piękny panie, <ch a="C"/>raz zobaczony w <ch a="a"/>technikolo<ch a="G"/>rze,</row>
      <row important_over="true"><ch a="F"/>Piszę do pana os<ch a="G"/>tatni <ch a="C"/>list.</row>
      <row important_over="true"><ch a="G"/>Już mi lusterko z tym <ch a="a"/>pana zdjęciem <ch a="F"/>też nie pomoże,</row>
      <row important_over="true"><ch a="C"/>Pora mi dzisiaj do <ch a="G"/>ślubu <ch a="C"/>iść.</row>
    </block>
    <block type="verse">
      <row important_over="never">Mój piękny panie, ja go nie kocham, taka jest prawda,</row>
      <row important_over="never">Pan główną rolę gra w każdym śnie.</row>
      <row important_over="never">Ale dziewczyna przez życie nie może iść całkiem sama,</row>
      <row important_over="never">Życie jest życiem, pan przecież wie.</row>
    </block>
    <block type="chorus">
      <row important_over="true"><ch a="F"/>Już mi <ch a="G"/>niosą suknię z we<ch a="C"/>lonem, <ch a="a"/></row>
      <row important_over="false"><ch a="F"/>Już Cy<ch a="G"/>ganie czekają z mu<ch a="C"/>zyką, <ch a="a"/></row>
      <row important_over="false"><ch a="F"/>Koń do <ch a="G"/>taktu zamiata o<ch a="C"/>gonem, <ch a="a"/></row>
      <row important_over="false"><ch a="F"/>Mendel<ch a="G"/>sonem stukają ko<ch a="C"/>pyta. <ch a="G"/></row>
    </block>
    <block type="verse">
      <row important_over="never">Jeszcze ryżem sypną na szczęście,</row>
      <row important_over="never">Gości tłum coś fałszywie odśpiewa,</row>
      <row important_over="never">Złoty krążek mi wcisną na rękę</row>
      <bis times="3">
        <row important_over="true">I po<ch a="F"/>wiozą mnie <ch a="G"/>windą do <ch a="C"/>nieba. <ch a="G"/></row>
      </bis>
    </block>
    <block type="verse">
      <row important_over="never">Mój piękny panie, z tego wszystkiego nie mogłam zasnąć,</row>
      <row important_over="never">Więc nie mógł mi się pan przyśnić dziś.</row>
      <row important_over="never">I tak odchodzę bez pożegnania, jakby znienacka,</row>
      <row important_over="never">Ktoś między nami zatrzasnął drzwi.</row>
    </block>
    <blocklink blocknb="3"/>
  </lyric>
  <music metre="4/4">
    <guitar barre="0"/>
  </music>
  <album>Teatr na drodze</album>
  <genre>pop</genre>
  <status>
    <done>
      <text/>
      <authors/>
      <chords>chord positioning</chords>
    </done>
    <verificators>
      <verificator>Krzysiek Cz.</verificator>
      <verificator>https://bibliotekapiosenki.pl/utwory/Winda_do_nieba</verificator>
      <verificator>https://spiewnik.wywrota.pl/dwa-plus-jeden/winda-do-nieba</verificator>
    </verificators>
  </status>
</song>

=== spiewaj/songbook/songs/pl/poezja/Krakow_Piwna_7.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Kraków, Piwna 7">
	<alias/>
	<text_author type="solo">Andrzej Sikorowski</text_author>
	<comment/>
	<composer type="solo">Andrzej Sikorowski</composer>
	<artist type="band">Pod Budą</artist>
	<translator/>
	<original_title/>
	<lyric>
		<block type="verse">
			<row important_over="true">B<ch a="C"/>yłem u wróżki – Piwna si<ch a="F"/>ed<ch a="G"/>em,<ch a="C"/></row>
			<row important_over="true">Wys<ch a="e"/>okie, kręte sch<ch a="a"/>od<ch a="e"/>y.<ch a="G"/></row>
			<row important_over="true">I<ch a="C"/>le mi jeszcze, chciałem wi<ch a="F"/>edz<ch a="G"/>ieć,<ch a="C"/></row>
			<row important_over="false">Upł<ch a="e"/>ynie w Wiśle w<ch a="a"/>od<ch a="e"/>y?<ch a="G"/></row>
			<row important_over="false">J<ch a="C"/>aka mnie kiedyś czeka bi<ch a="F"/>ed<ch a="G"/>a,<ch a="C"/></row>
			<row important_over="false">Lub j<ch a="e"/>akie urodz<ch a="a"/>aj<ch a="e"/>e?<ch a="G"/></row>
			<row important_over="false">Cz<ch a="C"/>y mi gitarę przyjdzie sprz<ch a="F"/>ed<ch a="G"/>ać,<ch a="C"/></row>
			<row important_over="false">Czy l<ch a="e"/>ecieć na Haw<ch a="a"/>aj<ch a="e"/>e?<ch a="G"/></row>
			<row important_over="true">A wr<ch a="a"/>óżka p<ch a="e"/>uka</row>
			<row important_over="true">W szkl<ch a="a"/>aną k<ch a="e"/>ulę</row>
			<row important_over="true">I m<ch a="a"/>ówi do mnie cz<ch a="e"/>ul<ch a="G"/>e:</row>
		</block>
		<block type="chorus">
			<row important_over="true">Przed t<ch a="C"/>obą sł<ch a="G"/>aw<ch a="C"/>a,</row>
			<row important_over="false">Wi<ch a="C"/>eczna zab<ch a="G"/>aw<ch a="C"/>a,</row>
			<row important_over="true">Wsz<ch a="F"/>ystko jak z n<ch a="G"/>ut,</row>
			<row important_over="false">Pi<ch a="F"/>eniędzy w br<ch a="G"/>ód.</row>
			<row important_over="false">Wspani<ch a="C"/>ałe pł<ch a="G"/>yt<ch a="C"/>y,</row>
			<row important_over="false">Pi<ch a="C"/>ękne kobi<ch a="G"/>et<ch a="C"/>y,</row>
			<row important_over="false">Zdr<ch a="F"/>owie jak dzw<ch a="G"/>on,</row>
			<row important_over="false">Wyg<ch a="F"/>odny tr<ch a="G"/>on.</row>
		</block>
		<block type="verse">
			<row important_over="false">Ż<ch a="C"/>egnam staruszkę lekki c<ch a="F"/>ał<ch a="G"/>y<ch a="C"/></row>
			<row important_over="false">I r<ch a="e"/>uszam w dół po sch<ch a="a"/>od<ch a="e"/>ach,<ch a="G"/></row>
			<row important_over="false">N<ch a="C"/>agle potykam się o m<ch a="F"/>ał<ch a="G"/>y<ch a="C"/></row>
			<row important_over="false">Wyj<ch a="e"/>ątek w jej progn<ch a="a"/>oz<ch a="e"/>ach.<ch a="G"/></row>
			<row important_over="false">I m<ch a="C"/>yślę tak, spadając z h<ch a="F"/>uki<ch a="G"/>em,<ch a="C"/></row>
			<row important_over="false">N<ch a="e"/>iby dojrzała gr<ch a="a"/>uszk<ch a="e"/>a:<ch a="G"/></row>
			<row important_over="false">W k<ch a="C"/>ońcu przyszedłem po na<ch a="F"/>uk<ch a="G"/>ę,<ch a="C"/></row>
			<row important_over="false">Z<ch a="e"/>atem niech żyje wr<ch a="a"/>óżk<ch a="e"/>a!<ch a="G"/></row>
			<row important_over="false">Niech cz<ch a="a"/>ęściej p<ch a="e"/>uka</row>
			<row important_over="false">W szkl<ch a="a"/>aną k<ch a="e"/>ulę</row>
			<row important_over="false">I m<ch a="a"/>ówi do nas cz<ch a="e"/>ul<ch a="G"/>e:</row>
		</block>
		<block type="chorus">
			<bis times="2">
				<row important_over="false">Przed w<ch a="C"/>ami sł<ch a="G"/>aw<ch a="C"/>a,</row>
				<row important_over="false">Wi<ch a="C"/>eczna zab<ch a="G"/>aw<ch a="C"/>a,</row>
				<row important_over="false">Wsz<ch a="F"/>ystko jak z n<ch a="G"/>ut,</row>
				<row important_over="false">Pi<ch a="F"/>eniędzy w br<ch a="G"/>ód,</row>
				<row important_over="false">Wspani<ch a="C"/>ałe pł<ch a="G"/>yt<ch a="C"/>y,</row>
				<row important_over="false">Pi<ch a="C"/>ękne kobi<ch a="G"/>et<ch a="C"/>y,</row>
				<row important_over="false">Zdr<ch a="F"/>owie jak dzw<ch a="G"/>on,</row>
				<row important_over="false">Wyg<ch a="F"/>odny tr<ch a="G"/>on.</row>
			</bis>
		</block>
	</lyric>
	<music metre="4/4">
		<guitar barre="2"/>
	</music>
	<keywords/>
	<album>Zmowa z zegarem</album>
	<genre>Poezja śpiewana</genre>
	<status>
		<done>
			<text/>
			<authors/>
			<chords>chord positioning</chords>
		</done>
		<verificators>
			<verificator>Paweł Budzyński</verificator>
		</verificators>
		<to_do/>
	</status>
</song>

=== spiewaj/songbook/songs/pl/poezja/Mur_2.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Mur (L'Estaca)">
	<alias>Mur 2, L'Estaca, Stary Siset</alias>
	<text_author type="solo">Lluís Llach</text_author>
	<comment>Przekład słynnej katalońskiej pieśni „L'Estaca” (1968) w wykonaniu Zespołu Reprezentacyjnego.</comment>
	<composer type="solo">Lluís Llach</composer>
	<artist type="band">Zespół Reprezentacyjny</artist>
	<translator>Agnieszka Rurarz</translator>
	<original_title>L'Estaca</original_title>
	<lyric>
		<block type="verse">
			<row important_over="true"><ch a="e"/>Stary Siset kiedyś m<ch a="H7"/>ówił m<ch a="e"/>i,</row>
			<row important_over="true">Staliśmy w br<ch a="H7"/>amie, był świt,</row>
			<row important_over="true">Gdy oczekiwal<ch a="C"/>iśmy na sł<ch a="H7"/>ońca wsch<ch a="C"/>ód<ch a="a"/></row>
			<row important_over="true">I samochod<ch a="e"/>ów r<ch a="H7"/>ósł sz<ch a="e"/>um.</row>
			<row important_over="true">Mówił mi: „Czy m<ch a="H7"/>uru nie w<ch a="e"/>idzisz?</row>
			<row important_over="true">Wszystkich nas trz<ch a="H7"/>yma ten mur.</row>
			<row important_over="true">Gdy ni<ch a="C"/>e będziemy br<ch a="H7"/>onić si<ch a="C"/>ę,<ch a="a"/></row>
			<row important_over="true">Zagr<ch a="e"/>odzi nam k<ch a="H7"/>ażdą z dr<ch a="e"/>óg”.</row>
		</block>
		<block type="chorus">
			<row important_over="true">Gdy uderz<ch a="H7"/>ymy, runie m<ch a="e"/>ur,</row>
			<row important_over="true">Nie może prz<ch a="H7"/>ecież wiecznie trw<ch a="e"/>ać,</row>
			<row important_over="true">Na pewno r<ch a="a"/>unie, runie, r<ch a="e"/>unie,</row>
			<row important_over="true">Nie pozost<ch a="H7"/>anie po nim śl<ch a="e"/>ad.</row>
			<row important_over="false">Jeśli uderz<ch a="H7"/>ysz mocno t<ch a="e"/>u,</row>
			<row important_over="false">A ja uderz<ch a="H7"/>ę mocno t<ch a="e"/>am,</row>
			<row important_over="false">Na pewno r<ch a="a"/>unie, runie, r<ch a="e"/>unie,</row>
			<row important_over="false">I wolny b<ch a="H7"/>ędzie cały świ<ch a="e"/>at.</row>
		</block>
		<block type="verse">
			<row important_over="false">Lecz minęło j<ch a="e"/>uż wiele l<ch a="H7"/>at,<ch a="e"/></row>
			<row important_over="false">Ręce mam st<ch a="H7"/>arte do krwi,</row>
			<row important_over="false">A gdy czuję, że s<ch a="C"/>ił mi br<ch a="H7"/>ak,<ch a="C"/><ch a="a"/></row>
			<row important_over="false">Mur r<ch a="e"/>ośnie w<ch a="H7"/>yższy niż b<ch a="e"/>ył.</row>
			<row important_over="false">Wiem już, że l<ch a="H7"/>edwo się trz<ch a="e"/>yma,</row>
			<row important_over="false">Lecz ciężko r<ch a="H7"/>uszyć go stąd,</row>
			<row important_over="false">Nawet gd<ch a="C"/>y czuję przypł<ch a="H7"/>yw s<ch a="C"/>ił...<ch a="a"/></row>
			<row important_over="false">Powt<ch a="e"/>órz, Sis<ch a="H7"/>ecie, pieśń sw<ch a="e"/>ą!</row>
		</block>
		<blocklink blocknb="2"/>
		<block type="verse">
			<row important_over="false">Stary Siset ni<ch a="e"/>e mówi n<ch a="H7"/>ic,<ch a="e"/></row>
			<row important_over="false">Słowa porw<ch a="H7"/>ał zły wiatr,</row>
			<row important_over="false">Dokąd — on j<ch a="C"/>eden t<ch a="H7"/>ylko wi<ch a="C"/>e,<ch a="a"/></row>
			<row important_over="false">Ja w br<ch a="e"/>amie tkwi<ch a="H7"/>ę cały cz<ch a="e"/>as.</row>
			<row important_over="false">I gdy przych<ch a="H7"/>odzę, mówi wci<ch a="e"/>ąż,</row>
			<row important_over="false">Słyszę, jak r<ch a="H7"/>ośnie mój głos,</row>
			<row important_over="false">Śpiew<ch a="C"/>amy ostatnią Sis<ch a="H7"/>eta pi<ch a="C"/>eśń,<ch a="a"/></row>
			<row important_over="false">Tę, kt<ch a="e"/>órej na<ch a="H7"/>uczył nas <ch a="e"/>on.</row>
		</block>
		<blocklink blocknb="2"/>
	</lyric>
	<music metre="3/4">
		<guitar barre="0"/>
	</music>
	<keywords/>
	<album>Za nami noc...</album>
	<genre>Poezja śpiewana</genre>
	<status>
		<done>
			<text/>
			<authors/>
			<chords>chord positioning</chords>
		</done>
		<verificators>
			<verificator>Paweł Budzyński</verificator>
		</verificators>
		<to_do/>
	</status>
</song>

=== spiewaj/songbook/songs/pl/poezja/ballada_o_nocy_czerwcowej.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Ballada o nocy czerwcowej">
  <alias>Noc czerwcowa</alias>
  <text_author type="solo">Konstanty Ildefons Gałczyński</text_author>
  <comment>Pieśń ta powinna być wykonywana w rytmie walczyka</comment>
  <composer>Maryla Ochimowska - Teper</composer>
  <lyric>
    <block type="verse">
      <row important_over="true">Kiedy no<ch a="D"/>c się w powietrzu zaczy<ch a="e"/>na,</row>
      <row important_over="true">Wtedy n<ch a="G"/>oc jest jak młoda dziewczyn<ch a="D"/>a:</row>
      <row important_over="true">Wszystko cie<ch a="D"/>szy ją i wszystko śmies<ch a="e"/>zy,</row>
      <row important_over="true">Wszystko w rę<ch a="G"/>ce chciałaby brać<ch a="D"/>.</row>
    </block>
    <block type="verse">
      <row important_over="true">Diabeł du<ch a="D"/>żo jej daje w podar<ch a="e"/>ku</row>
      <row important_over="true">Gwiazd fałsz<ch a="G"/>ywych z gwiezdnego jarma<ch a="D"/>rku.</row>
      <row important_over="true">Noc te gwia<ch a="D"/>zdy do uszu przymier<ch a="e"/>za</row>
      <row important_over="true">I z gwiazda<ch a="G"/>mi chci<ch a="A7"/>ałaby spać.<ch a="D"/></row>
    </block>
    <block type="chorus">
      <bis times="2">
        <row important_over="true">Ja je<ch a="D"/>stem noc czerwcow<ch a="e"/>a.</row>
        <row important_over="true">Królo<ch a="G"/>wa jaśminow<ch a="D"/>a.</row>
        <row important_over="true">Zap<ch a="D"/>atrzcie się w moje ręc<ch a="e"/>e.</row>
        <row important_over="true">Wsłucha<ch a="A7"/>jcie się w śpiewny chód.<ch a="D"/></row>
      </bis>
    </block>
    <block type="verse">
      <row important_over="false">Ale zanim dur gwiezdny ją oplótł,<ch a="D"/><ch a="e"/></row>
      <row important_over="false">Idzie krokiem tanecznym przez ogród.<ch a="G"/><ch a="D"/></row>
      <row important_over="false">Do ogrodu przez senne ulice,<ch a="D"/><ch a="e"/></row>
      <row important_over="false">Dzwonią nocy ciężkie zausznice.<ch a="G"/><ch a="D"/></row>
    </block>
    <block type="verse">
      <row important_over="false">I po każdym tanecznym obrocie<ch a="D"/><ch a="e"/></row>
      <row important_over="false">Szmaragdami dzwonią kołki w plocie.<ch a="G"/><ch a="D"/></row>
      <row important_over="false">Wreszcie do nas pod same okna,<ch a="D"/><ch a="e"/></row>
      <row important_over="false">I tak tańczy i śpiewa nam:<ch a="G"/><ch a="A7"/><ch a="D"/></row>
    </block>
    <blocklink blocknb="3"/>
  </lyric>
  <keywords/>
  <genre>Poezja śpiewana</genre>
  <status>
    <done/>
    <verificators/>
  </status>
</song>

=== spiewaj/songbook/songs/pl/kabaret/plastikowa_biedronko.xml
<?xml version="1.0" encoding="utf-8"?>
<song xmlns="http://21wdh.staszic.waw.pl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://21wdh.staszic.waw.pl https://spiewaj.com/song.xsd" title="Plastikowa Biedronka">
  <comment>zwrotka dodatkowa gdzieś w środku: 
Kiedy w końcu nas kupili GD
 I do domu nas zawieźli e C
 To Ty na mnie spoglądałaś GD
 I się we mnie zakochałaś e C</comment>
  <lyric>
    <block type="verse">
      <row important_over="true">Gdy Cię pi<ch a="G"/>erwszy raz u<ch a="D"/>jrzałem </row>
      <row important_over="true">Wielkim t<ch a="e"/>irem zajech<ch a="C"/>ałaś </row>
      <row important_over="true">Ja się w T<ch a="G"/>obie zakoch<ch a="D"/>ałem </row>
      <row important_over="true">A Ty na m<ch a="e"/>nie nie<ch a="C"/> spojrza<ch a="G"/>łaś!</row>
    </block>
    <block type="chorus">
      <row important_over="true">Plastik<ch a="G"/>owa Biedr<ch a="D"/>onko, Ty m<ch a="e"/>oja koch<ch a="C"/>ana </row>
      <row important_over="true">Zo<ch a="G"/>stań moją ż<ch a="D"/>onką błagam Ci<ch a="e"/>ę n<ch a="C"/>a kolan<ch a="G"/>ach! </row>
    </block>
    <block type="verse">
      <row important_over="true">Gdy Cię drugi raz ujrzałem <ch a="G"/><ch a="D"/></row>
      <row important_over="true">Na sklepowej półce stałaś <ch a="e"/><ch a="C"/></row>
      <row important_over="true">Ja Ci list miłosny słałem<ch a="G"/><ch a="D"/></row>
      <row important_over="true">// Ja Cię wtedy pokochałem // <ch a="G"/><ch a="D"/></row>
      <row important_over="true">A Ty na mnie nie spojrzałaś! <ch a="e"/><ch a="C"/><ch a="G"/></row>
    </block>
    <blocklink blocknb="2"/>
    <block type="verse">
      <row important_over="false">Gdy Cię trzeci raz ujrzałem<ch a="G"/><ch a="D"/></row>
      <row important_over="false">Ty z szympansem mnie zdradziłaś<ch a="e"/><ch a="C"/></row>
      <row important_over="false">Ja mu wtedy pokazałem<ch a="G"/><ch a="D"/></row>
      <row important_over="false">Jaka jest pingwinia siła<ch a="e"/><ch a="C"/><ch a="G"/></row>
    </block>
    <blocklink blocknb="2"/>
    <block type="verse">
      <row important_over="false">To już koniec tej piosenki<ch a="G"/><ch a="D"/></row>
      <row important_over="false">Mój Ty widzu ukochany <ch a="e"/><ch a="C"/></row>
      <row important_over="false">Jeśli Ci się spodobała<ch a="G"/><ch a="D"/></row>
      <row important_over="false">To zaśpiewaj razem z nami! <ch a="e"/><ch a="C"/><ch a="G"/></row>
    </block>
    <blocklink blocknb="2"/>
  </lyric>
  <keywords/>
  <genre>Piosenka kabaretowa</genre>
  <status>
    <done/>
    <verificators/>
  </status>
</song>
